FROM eclipse-temurin:17-jdk-jammy
ARG JAR_FILE=target/service-a.jar
COPY ${JAR_FILE} /app/app.jar
# copy otel agent (pre-baked in compose volume or download in image)
COPY open-telemetry-javaagent.jar /opt/opentelemetry-javaagent.jar

ENV SPLUNK_HEC_URL=http://splunk:8088/services/collector
ENV SPLUNK_HEC_TOKEN=changeme
ENV OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250

EXPOSE 8080
ENTRYPOINT ["sh","-c","java -javaagent:/opt/opentelemetry-javaagent.jar -Dotel.exporter.jaeger.endpoint=${OTEL_EXPORTER_JAEGER_ENDPOINT} -Dotel.service.name=${SERVICE_NAME} -jar /app/app.jar"]
